---
title: "Materiales para el Taller"
---



::: {.callout-important appearance="default" icon="false"}
#### Importante!!

-   Durante el curso interactuaremos con [R](https://cran.r-project.org/) y [Quarto](https://quarto.org/) a través de [RStudio](https://www.rstudio.com/products/rstudio/). Se recomienda tener instaladas **versiones recientes** de los 3 programas. En [Info](info.qmd) tienes los links de instalación.

:::



## Slides

Durante el curso utilizaremos las siguientes **slides**:


- [Slides 01: Presentación](./slides/01_presentacion.qmd){target="_blank"}

- [Slides 02: Primeros pasos](./slides/02_primeros_pasos.qmd){target="_blank"}

- [Slides 03: Aprendiendo a escribir en QMD](./slides/03_aprendiendo_Qmd.qmd){target="_blank"}

- [Slides 04: Revealjs slides](./slides/04_revealjs.qmd){target="_blank"}

- [Slides 05: Webs/blogs con Quarto](./slides/05_primer_web.qmd){target="_blank"}

- [Slides 06: Más cosas con Quarto](./slides/06_mas_cosas.qmd){target="_blank"}


Si quieres, puedes descargar todas las slides en pdf [aquí](./slides/slides_en_pdf.zip){target="_blank"}, y en formato html [aquí](./slides/slides_en_html.zip){target="_blank"}.

## Tercera sesión del curso

En la tercera sesión del curso usaremos 2 Qprojects:

  - El Qproject llamado "quarto.tercer.dia" que puedes descargar [aquí](/cuestionario/quarto.tercer.dia.zip){target="_blank"} comprimido en formato .zip
  
  
  - El Qproject llamado "parametrised_reports" que puedes descargar [aquí](/cuestionario/parametrised_reports.zip){target="_blank"} comprimido en formato .zip



## Cuestionario

En la última sesión haremos algunas prácticas y ejercicios de este [cuestionario](./cuestionario/01_cuestionario.qmd){target="_blank"}.

Para resolver los ejercicios usaremos el Qproject llamado **"quarto.ejercicios"** que puedes descargar [aquí](/cuestionario/quarto.ejercicios.zip){target="_blank"} comprimido en formato .zip

## Blog

En los artículos del [blog](blog.qmd){target="_blank"} se desarrollan algunos de los tópicos que iremos viendo durante el curso.

<br>


## Logística (enlaces)

Son simplemente enlaces para mi, para tenerlos a mano por si los necesito durante las clases:

- [Etherpad](https://etherpad.wikimedia.org/p/curso_intro_DS_UV){target="_blank"}


- [RStudio Cloud Project: primer día](https://posit.cloud/content/6139160){target="_blank"} 


- [RStudio Cloud Project: segundo día](https://posit.cloud/content/4743159){target="_blank"}

- [RStudio Cloud Project: tercer día](https://posit.cloud/content/6164186){target="_blank"}

- [RStudio Cloud Project: tercer día; informes parametrizados](https://posit.cloud/content/6164148){target="_blank"}


 - [Programación y manejo de datos con R](https://perezp44.github.io/intro-ds-22-23-web/04-tutoriales.html){target="_blank"}


- [Curso de introduccióna R, SFPIE, 2023](https://perezp44.github.io/intro.R.sfpie.2023.web/){target="_blank"}


- Aula Virtual de la asignatura:  [Grupo PAS](https://aulavirtual.uv.es/course/view.php?id=55335){target="_blank"} y [Grupo PDI](https://aulavirtual.uv.es/course/view.php?id=55334){target="_blank"} 



<br>


## Bibliografía/Recursos 


Desde que **Quarto** se hizo publico con [We don't talk about Quarto](https://www.apreshill.com/blog/2022-04-we-dont-talk-about-quarto/){target="_blank"} ha sido un no parar de workshops, posts, etc ... En esta página tienes una selección de recursos sobre Quarto.

La **principal referencia** es la [web de Quarto](https://quarto.org/){target="_blank"}: **absolutamente fantástica**!!! En ella hay, entre otras secciones, una [Guide](https://quarto.org/docs/guide/){target="_blank"}, una [Reference](https://quarto.org/docs/reference/){target="_blank"} y una [Gallery](https://quarto.org/docs/gallery/){target="_blank"}.

A destacar también el listado de recursos [Awesome Quarto](https://github.com/mcanouil/awesome-quarto){target="_blank"} mantenida por Mickaël Canouil.


<br>

Para dudas, consejos, trucos:

- Quarto CLI-dev repo: [Issues](https://github.com/quarto-dev/quarto-cli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc){target="_blank"} and [Discussions](https://github.com/quarto-dev/quarto-cli/discussions){target="_blank"}.

-  Stackoverflow: preguntas sobre Quarto [aquí](https://stackoverflow.com/questions/tagged/quarto){target="_blank"}

- Tabla con "useful Quarto tips" de [Sharon Machlis](https://fosstodon.org/@smach){target="_blank"}, [aquí](https://apps.machlis.com/shiny/quartotips/){target="_blank"}

<br>

Entre los materiales sobre Quarto, **destacar los siguientes**:


- [Quarto tip a day](http://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/){target="_blank"}: Un blog de Mine Çetinkaya-Rundel con consejos y tips sobre Quarto.

- [ Get Started with Quarto](https://jthomasmock.github.io/quarto-2hr-webinar/){target="_blank"}: un workshop de Thomas Mock. El [video](https://youtu.be/yvi5uXQMvu4), y [otro video de 3h](https://www.youtube.com/watch?v=KnwQFph3s94&list=PL4IzsxWztPdmSeucR67EH_8_hzldqYZX4&index=8){target="_blank"}.

- [Beautiful Reports and Presentations with Quarto](https://thomasmock.quarto.pub/reports-presentations/#/title-slide){target="_blank"}: un workshop de Thomas Mock. El [video](https://www.youtube.com/watch?v=hbf7Ai3jnxY){target="_blank"} y el [repo](https://github.com/jthomasmock/quarto-reporting){target="_blank"}. 

- [Introducción a RMarkdown, creando reportes con R y Python en RStudio](https://www.youtube.com/watch?v=d8jSN998Mtw){target="_blank"}: workshop de Renzo Cáceres para LatinR 2022.

- [Making shareable documents with Quarto](https://openscapes.github.io/quarto-website-tutorial/){target="_blank"}: una web de Openscapes.

- [Quarto/RMarkdown - What’s Different?](https://laderast.github.io/qmd_rmd/#/title-slide){target="_blank"}: unas slides de Ted Laderas.

- [Rstudio::conf(2022) Playlist](https://www.youtube.com/playlist?list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH){target="_blank"}:  la presentación en sociedad de Quarto con varias charlas sobre Quarto, [Hello Quarto: Share, Collaborate, Teach, Reimagine](https://www.youtube.com/watch?v=p7Hxu4coDl8&list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH&index=4){target="_blank"}, [Websites & Books & Blogs, oh my! Creating Rich Content with Quarto](https://www.youtube.com/watch?v=A9QRN4cpsDY&list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH&index=49){target="_blank"}, [Quarto for the Curious ](https://www.youtube.com/watch?v=mrvhk2XUfWo&list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH&index=55){target="_blank"} entre otras.  

-  [Rstudio::conf(2022) Workshops](https://github.com/rstudio-conf-2022){target="_blank"}: por ejemplo, [Get Started with Quarto](https://github.com/rstudio-conf-2022/get-started-quarto){target="_blank"} o [Rmarkdown to Quarto](https://github.com/rstudio-conf-2022/rmd-to-quarto){target="_blank"}.

- [Reproducible authoring with Quarto](https://www.youtube.com/watch?v=6p4vOKS6Xls){target="_blank"}: un vídeo de Mine Çetinkaya-Rundel donde se hace evidente las ventajas de Quarto y la utilidad del editor visual de RStudio. Sus slides [aquí](https://mine-cetinkaya-rundel.github.io/2022-repro-toronto/#/title-slide){target="_blank"}.


- [Building a blog with Quarto](https://ivelasq.quarto.pub/building-a-blog-with-quarto/){target="_blank"}: un workshop de Isabella Velásquez acerca de cómo construir un blog con Quarto. El [repo de los ejercicios](https://github.com/ivelasq/build-your-own-blog-exercises){target="_blank"}, [video](https://www.youtube.com/watch?v=CVcvXfRyfE0){target="_blank"} y [RStudioCloud project]( https://rstudio.cloud/project/4404816){target="_blank"}.

- [Websites & Books & Blogs, oh my! Creating Rich Content with Quarto](https://www.youtube.com/watch?v=A9QRN4cpsDY&list=PL9HYL-VRX0oTOwqzVtL_q5T8MNrzn0mdH&index=49){target="_blank"}: ponencia de Devin Pastoor en el marco de RStudio::conf(2022).



<br>

##### Otros recursos

- Una fantástica [guía sobre **Markdown**](https://www.markdownguide.org/){target="_blank"}

##### Más recursos

- [Aquí](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html#create-your-own-series) y [aquí](https://ellakaye.co.uk/posts/2022-12-11_welcome-quarto/) dos posts sobre tunear un Quarto blog
